export const metadata = {
  title: "ChatGPT Clone",
  description: "Generated by Next.js",
};


import "@/styles/globals.css"


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="flex">

          {/* Sidebar */}

          {/* ClientProvider - Notification */}

          <div className="bg-[#343541] flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
